# Generated by Django 4.2.4 on 2023-08-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('content_name', models.CharField(max_length=255)),
                ('content_image', models.URLField()),
                ('content_type', models.CharField(max_length=55)),
                ('release_year', models.IntegerField()),
            ],
        ),
    ]
