# Generated by Django 4.2.4 on 2023-08-30 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('top_rank', models.IntegerField()),
                ('image', models.URLField()),
                ('duration', models.IntegerField()),
                ('rating', models.FloatField()),
                ('genres', models.JSONField()),
                ('some_plot', models.TextField()),
                ('full_plot', models.TextField()),
                ('is_watched', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
