# Generated by Django 4.2.4 on 2023-08-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='imdb_id',
            field=models.CharField(default='no_id', max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
