# Generated by Django 4.2.4 on 2023-08-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.CharField(max_length=255),
        ),
    ]
