# Generated by Django 4.2.4 on 2023-08-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0002_alter_content_content_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
