# Generated by Django 4.2.4 on 2023-08-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer_app', '0003_delete_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('top_rank', models.FloatField()),
                ('image', models.URLField()),
                ('duration', models.IntegerField()),
                ('rating', models.FloatField()),
                ('genres', models.JSONField()),
                ('some_plot', models.TextField()),
                ('full_plot', models.TextField()),
            ],
        ),
    ]
