# Generated by Django 4.2.4 on 2023-08-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0005_alter_content_top_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizer_app.content')),
            ],
            bases=('organizer_app.content',),
        ),
    ]
