# Generated by Django 4.2.4 on 2023-08-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0006_deletedcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedContent',
        ),
    ]
