# Generated by Django 4.2.4 on 2023-08-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0009_alter_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
    ]
