# Generated by Django 4.2.4 on 2023-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0010_content_is_watched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('image', models.URLField()),
                ('duration', models.IntegerField()),
                ('genres', models.JSONField()),
            ],
        ),
    ]
