# Generated by Django 4.2.4 on 2023-08-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0011_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
