# Generated by Django 4.2.4 on 2023-08-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0013_content_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='imdb_id',
            field=models.CharField(default='no id', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
