# Generated by Django 4.2.4 on 2023-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0014_content_imdb_id_alter_content_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('image', models.URLField()),
                ('duration', models.IntegerField()),
                ('genres', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='imdb_id',
        ),
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
