# Generated by Django 4.2.4 on 2023-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0015_movie_remove_content_imdb_id_remove_content_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='content',
            name='movie_id',
            field=models.CharField(default='no id', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
