# Generated by Django 4.2.4 on 2023-08-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0018_movie_remove_content_movie_id_alter_content_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
